import { select, multiselect, confirm, spinner, log } from "@clack/prompts";
import fs from "fs-extra";
import path from "path";
import { detect } from "detect-package-manager";
import { exec } from "child_process";
import { promisify } from "util";

const execAsync = promisify(exec);

export async function init(args: string[]) {
  const adapter = (await select({
    message: "Which database adapter would you like to use?",
    options: [
      { value: "drizzle", label: "Drizzle ORM" },
      { value: "prisma", label: "Prisma" },
      { value: "mongodb", label: "MongoDB" },
    ],
  })) as string;

  let dialect: string | undefined;
  if (adapter === "drizzle" || adapter === "prisma") {
    dialect = (await select({
      message: "Which database dialect would you like to use?",
      options: [
        { value: "pg", label: "PostgreSQL" },
        { value: "mysql", label: "MySQL" },
        { value: "sqlite", label: "SQLite" },
      ],
    })) as string;
  }

  const features = await multiselect({
    message: "Which auth features would you like to enable?",
    options: [
      { value: "passwords", label: "Password-based Auth" },
      { value: "magic-link", label: "Magic Links" },
      { value: "oauth", label: "OAuth Providers" },
    ],
    required: false,
  });

  const onboarding = await confirm({
    message: "Would you like to generate an onboarding flow?",
    initialValue: true,
  });

  const s = spinner();
  s.start("Generating auth configuration...");

  const authDir = path.join(process.cwd(), "lib");
  await fs.ensureDir(authDir);

  let adapterImport = "";
  let adapterCall = "";

  if (adapter === "drizzle") {
    const subpath = dialect ? `/${dialect}` : "";
    adapterImport = `import { createDrizzleAdapter } from "@bolkauth/adapter-drizzle${subpath}";\nimport { db } from "./db";`;
    adapterCall = `createDrizzleAdapter(db)`;
  } else if (adapter === "prisma") {
    adapterImport = `import { createPrismaAdapter } from "@bolkauth/adapter-prisma";\nimport { PrismaClient } from "@prisma/client";\nconst prisma = new PrismaClient();`;
    adapterCall = `createPrismaAdapter(prisma)`;
  } else if (adapter === "mongodb") {
    adapterImport = `import { createMongoDBAdapter } from "@bolkauth/adapter-mongodb";\nimport { db } from "./db";`;
    adapterCall = `createMongoDBAdapter(db)`;
  }

  const authContent = `// Generated by @bolkauth/cli
import { createBolkAuth } from "@bolkauth/core";
${adapterImport}

export const auth = createBolkAuth({
  adapter: ${adapterCall},
  secret: process.env.BOLKAUTH_SECRET || "your-32-character-secret-key-here",
  emailAndPassword: { enabled: true },${onboarding ? `\n  onboarding: { enabled: true, requiredForAccess: true, redirectUrl: "/onboarding" },` : ''}
});
`;

  await fs.writeFile(path.join(authDir, "auth.ts"), authContent.trim() + "\n");

  s.stop("Auth configuration generated at lib/auth.ts");

  const pm = await detect();
  s.start(`Installing dependencies using ${pm}...`);

  const pkgName =
    adapter === "drizzle"
      ? "@bolkauth/adapter-drizzle"
      : adapter === "prisma"
      ? "@bolkauth/adapter-prisma"
      : "@bolkauth/adapter-mongodb";

  try {
    await execAsync(`${pm} add @bolkauth/core ${pkgName}`);
    s.stop("Dependencies installed successfully.");
  } catch (err) {
    s.stop("Failed to install dependencies.");
    log.error((err as Error).message);
  }
}
