import { select, multiselect, confirm, spinner, log } from "@clack/prompts";
import fs from "fs-extra";
import path from "path";
import { detect } from "detect-package-manager";
import { exec } from "child_process";
import { promisify } from "util";

const execAsync = promisify(exec);

export async function init(args: string[]) {
  const adapter = await select({
    message: "Which database adapter would you like to use?",
    options: [
      { value: "drizzle", label: "Drizzle ORM" },
      { value: "prisma", label: "Prisma" },
    ],
  });

  const features = await multiselect({
    message: "Which auth features would you like to enable?",
    options: [
      { value: "passwords", label: "Password-based Auth" },
      { value: "magic-link", label: "Magic Links" },
      { value: "oauth", label: "OAuth Providers" },
    ],
    required: false,
  });

  const onboarding = await confirm({
    message: "Would you like to generate an onboarding flow?",
    initialValue: true,
  });

  const s = spinner();
  s.start("Generating auth configuration...");

  const authDir = path.join(process.cwd(), "lib");
  await fs.ensureDir(authDir);

  const adapterImport = adapter === 'drizzle'
    ? `import { createDrizzleAdapter } from "@authflow/adapter-drizzle";\nimport { db } from "./db";`
    : `import { createPrismaAdapter } from "@authflow/adapter-prisma";\nimport { PrismaClient } from "@prisma/client";\nconst prisma = new PrismaClient();`;

  const adapterCall = adapter === 'drizzle'
    ? `createDrizzleAdapter(db)`
    : `createPrismaAdapter(prisma)`;

  const authContent = `// Generated by @authflow/cli
import { createAuthFlow } from "@authflow/core";
${adapterImport}

export const auth = createAuthFlow({
  adapter: ${adapterCall},
  secret: process.env.AUTHFLOW_SECRET || "your-32-character-secret-key-here",
  emailAndPassword: { enabled: true },${onboarding ? `\n  onboarding: { enabled: true, requiredForAccess: true, redirectUrl: "/onboarding" },` : ''}
});
`;

  await fs.writeFile(path.join(authDir, "auth.ts"), authContent.trim() + "\n");

  s.stop("Auth configuration generated at lib/auth.ts");

  const pm = await detect();
  s.start(`Installing dependencies using ${pm}...`);
  
  const pkgName = adapter === 'drizzle' ? '@authflow/adapter-drizzle' : '@authflow/adapter-prisma';
  try {
    await execAsync(`${pm} add @authflow/core ${pkgName}`);
    s.stop("Dependencies installed successfully.");
  } catch (err) {
    s.stop("Failed to install dependencies.");
    log.error((err as Error).message);
  }
}
